---

- debug:
      msg: "Deploying {{ commit_hash.stdout }}"

- name: Change owner
  command: chown -R www-data:www-data {{ web_dir }}/{{ project_name }}/{{ commit_hash.stdout }}

- name: Change directory access
  command: chmod -R u=rwx,g=rx,o=r {{ web_dir }}/{{ project_name }}/{{ commit_hash.stdout }}

- name: Create link
  file:
   path: "{{ web_dir }}/{{ project_name }}/current"
   src: "{{ web_dir }}/{{ project_name }}/{{ commit_hash.stdout }}"
   state: link
   owner: www-data
   mode: "u=rwx,g=rx,o=r"
