---

- debug:
      msg: "Deploying {{ commit_hash.stdout }}"

- name: Change directory access
  file:
   path: "{{ web_dir }}/{{ project_name }}/{{ commit_hash.stdout }}"
   state: touch
   mode: "u=rwx,g=rx,o=r"
   owner: www-data
   group: www-data

- name: Create link
  file:
   path: "{{ web_dir }}/{{ project_name }}/current"
   src: "{{ web_dir }}/{{ project_name }}/{{ commit_hash.stdout }}"
   state: link
   mode: 0755
