---

  - name: Create project directory
    file:
     path: "{{ web_dir }}/{{ project_name }}"
     state: directory
     mode: 0775

  - name: Checkout project
    git:
      dest: "{{ tmp_dir }}/{{ project_name }}"
      repo: "{{ git_repo }}"
      version: "{{ git_branch }}"

  - name: Get last commit hash
    command: git rev-parse HEAD
    args:
      chdir: "{{ tmp_dir }}/{{ project_name }}"
    register: commit_hash

  - debug:
      msg: "Deploying {{ commit_hash.stdout }}"

  - name: Moving from tmp
    command: mv {{ tmp_dir }}/{{ project_name }} {{ web_dir }}/{{ project_name }}/{{ commit_hash.stdout }}

  - name: Running composer
    command: composer install
    args:
      chdir: "{{ web_dir }}/{{ project_name }}/{{ commit_hash.stdout }}"

  - name: Running tests
    command: bin/phpspec r
    args:
      chdir: "{{ web_dir }}/{{ project_name }}/{{ commit_hash.stdout }}"

  - name: Change directory access
    file:
     path: "{{ web_dir }}/{{ project_name }}/{{ commit_hash.stdout }}"
     state: touch
     mode: "u+rwx,g-wx,o-rwx"
     owner: www-data
     group: www-data

  - name: Create link
    file:
     path: "{{ web_dir }}/{{ project_name }}/current"
     src: "{{ web_dir }}/{{ project_name }}/{{ commit_hash.stdout }}"
     state: link
     mode: 0755