---
# tasks file for build-parameters

- debug:
    var: {{ ansible_env.BEWAMO_DATABASE_PORT }}

- name: Generate parameters file
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items: "{{ build_parameters.files }}"
