---
# tasks file for build-parameters

- debug:
    var: "{{ ansible_env.HOME }}"

- name: Generate parameters file
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items: "{{ build_parameters.files }}"
