# tasks file for npm
---
- name: Download Debian Source
  get_url:
    url: https://deb.nodesource.com/setup_{{ npm.node_js_version }}
    dest: /tmp/setup
    mode: 0755
    validate_certs: no
  register: debianSource

- name: Install Debian Source
  shell:
    bash /tmp/setup
  when: debianSource.changed

- name: Update APT Cache
  apt:
    update_cache=yes
  when: debianSource.changed

- name: Install NodeJS {{ npm.node_js_version }}
  apt: pkg=nodejs state=present